[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "VirTex"
authors = [{name = "Avanish", email = "avanish@VirTex"}]
dynamic = ["version", "description"]
